# .goreleaser.yaml
project_name: vilesql

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    binary: vilesql
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - .env

nfpms:
  - id: packages
    package_name: vilesql
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: VileSQL
    homepage: https://github.com/imrany/vilesql
    maintainer: imrany imranmat254@gmail.com
    description: |-
      VileSQL - SQLite Database Management Tool
    license: GPL-3.0-only
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - ca-certificates
    recommends:
      - sqlite3
    bindir: /usr/bin
    contents:
      - src: .env
        dst: /etc/vilesql/.env
        type: config
      # Pre-create system data directory
      - dst: /var/lib/vilesql
        type: dir
        file_info:
          mode: 0755
          owner: root
          group: root
    scripts:
      postinstall: "scripts/postinstall.sh"
      # postupgrade: "scripts/postupgrade.sh"
      preremove: "scripts/preremove.sh"
      postremove: "scripts/postremove.sh"

# Homebrew tap
brews:
  - name: vilesql
    homepage: https://github.com/imrany/vilesql
    description: SQLite Database Management Tool
    license: GPL-3.0-only
    repository:
      owner: imrany
      name: vilesql
    caveats: |
      VileSQL will create a data directory at ~/.vilesql on first run.
      This directory contains your database files and configuration.
     
      Data locations:
        - ~/.vilesql (user data)
        - ~/Library/Application Support/vilesql (macOS)
      
      To specify a custom data directory, use:
        vilesql --data-dir /path/to/your/data
      
      To completely uninstall VileSQL and remove all data:
        brew uninstall vilesql
        rm -rf ~/.vilesql
        rm -rf ~/Library/Application\ Support/vilesql

      Or use the built-in uninstall command before removing:
        vilesql uninstall --remove-data
        brew uninstall vilesql

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: imrany
    name: vilesql
  draft: true
  prerelease: auto
  name_template: "Release {{.Version}}"
  header: |
    ## VileSQL {{.Version}}

    ## **📌 Features**
    ✔ **Cloud-hosted SQLite databases** – No need to install or configure SQLite manually.  
    ✔ **Secure authentication with API tokens** – Ensure **safe and private** data access.  
    ✔ **Intuitive Control Panel** – Manage users, queries, and settings with a **user-friendly dashboard**.  
    ✔ **Automated Backups** – Never lose your data, even in critical operations.  
    ✔ **Query Execution & Monitoring** – Track real-time database activity in the **control panel**.  
    ✔ **Performance Optimization** – Indexing and caching mechanisms for **faster queries**.  
    ✔ **Cross-Platform Compatibility** – Works seamlessly on **Linux, macOS, and Windows**.  
    
    ### Installation
    
    **Homebrew (macOS):**
    ```bash
    brew install imrany/tap/vilesql
    ```
    
    **Debian/Ubuntu:**
    ```bash
    wget https://github.com/imrany/vilesql/releases/download/{{.Tag}}/vilesql_{{.Version}}_linux_amd64.deb
    sudo dpkg -i vilesql_{{.Version}}_linux_amd64.deb
    ```
    
    **Manual Installation:**
    Download the appropriate binary for your platform from the assets below.
  footer: |
    ### Support
    
    - 📚 Documentation: https://github.com/imrany/vilesql#readme
    - 🐛 Report Issues: https://github.com/imrany/vilesql/issues
    - 💬 Discussions: https://github.com/imrany/vilesql/discussions
    
    **Full Changelog**: https://github.com/imrany/vilesql/compare/{{.PreviousTag}}...{{.Tag}}