# Docker Compose for development and production
version: '3.8'

services:
  vilesql:
    build: .
    # Or use the pre-built image:
    # image: ghcr.io/imrany/vilesql:latest
    ports:
      - "5000:5000"
    volumes:
      - vilesql_data:/var/lib/vilesql
      - ./config:/etc/vilesql:ro
    environment:
      - VILESQL_DATA_DIR=/var/lib/vilesql
      - PORT=5000
      - HOST=0.0.0.0
      - SESSION_KEY=your-session-key
      - COOKIE_STORE_KEY=your-cookie-store-key
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  vilesql_data:
    driver: local