# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vilesql < Formula
  desc "SQLite Database Management Tool with cloud hosting and secure authentication"
  homepage "https://github.com/imrany/vilesql"
  version "0.7.0"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/imrany/vilesql/releases/download/v0.7.0/vilesql_0.7.0_Darwin_all.tar.gz"
    sha256 "5420d101b594c4a7fb07e6ddc05be6306731562a59e96a0ac94498406b25e02c"

    def install
      bin.install "vilesql"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/imrany/vilesql/releases/download/v0.7.0/vilesql_0.7.0_Linux_x86_64.tar.gz"
        sha256 "94420976bc9c7228ad522f5ab477342d277ea14bc9ce4a6fd5d14f4890523ecb"

        def install
          bin.install "vilesql"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/imrany/vilesql/releases/download/v0.7.0/vilesql_0.7.0_Linux_arm64.tar.gz"
        sha256 "e7b9b6ef126b252a5b6468e04c24db0f329206307ec201cd2484a016f32fe0ad"

        def install
          bin.install "vilesql"
        end
      end
    end
  end

  def caveats
    <<~EOS
      VileSQL will create a data directory at ~/.vilesql on first run.
      This directory contains your database files and configuration.

      Data locations:
        - ~/.vilesql (user data)
        - ~/Library/Application Support/vilesql (macOS)

      To specify a custom data directory, use:
        vilesql --data-dir /path/to/your/data

      Upgrade VileSQL:
        brew upgrade vilesql
        # or use the built-in upgrade command:
        vilesql upgrade

      Check for updates:
        vilesql upgrade --check-only

      To completely uninstall VileSQL and remove all data:
        vilesql uninstall --remove-data
        brew uninstall vilesql

      Or backup before uninstalling:
        vilesql uninstall --remove-data --backup-data
        brew uninstall vilesql
    EOS
  end
end
