# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vilesql < Formula
  desc "SQLite Database Management Tool with cloud hosting and secure authentication"
  homepage "https://github.com/imrany/vilesql"
  version "0.6.0"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/imrany/vilesql/releases/download/v0.6.0/vilesql_0.6.0_Darwin_all.tar.gz"
    sha256 "af96e64492aa7851f6b7b357e04e249db60a79e3422148bbf83d318b0390a5a8"

    def install
      bin.install "vilesql"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/imrany/vilesql/releases/download/v0.6.0/vilesql_0.6.0_Linux_x86_64.tar.gz"
        sha256 "51afef6cb68f7cf1f40e3714cc04e6a1932d2d717561900cca26da6343289607"

        def install
          bin.install "vilesql"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/imrany/vilesql/releases/download/v0.6.0/vilesql_0.6.0_Linux_arm64.tar.gz"
        sha256 "5bcac304dfb65604876474115e843f116b5de7395e7a6511d00c11f4ae132c42"

        def install
          bin.install "vilesql"
        end
      end
    end
  end

  def caveats
    <<~EOS
      VileSQL will create a data directory at ~/.vilesql on first run.
      This directory contains your database files and configuration.

      Data locations:
        - ~/.vilesql (user data)
        - ~/Library/Application Support/vilesql (macOS)

      To specify a custom data directory, use:
        vilesql --data-dir /path/to/your/data

      Upgrade VileSQL:
        brew upgrade vilesql
        # or use the built-in upgrade command:
        vilesql upgrade

      Check for updates:
        vilesql upgrade --check-only

      To completely uninstall VileSQL and remove all data:
        vilesql uninstall --remove-data
        brew uninstall vilesql

      Or backup before uninstalling:
        vilesql uninstall --remove-data --backup-data
        brew uninstall vilesql
    EOS
  end
end
