# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vilesql < Formula
  desc "SQLite Database Management Tool with cloud hosting and secure authentication"
  homepage "https://github.com/imrany/vilesql"
  version "0.11.5"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/imrany/vilesql/releases/download/v0.11.5/vilesql_0.11.5_Darwin_all.tar.gz"
    sha256 "7a17f9c2f6ad7da1d1e2375a2425abaa494c047ed824c35e8fc2517be8794e2f"

    def install
      bin.install "vilesql"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/imrany/vilesql/releases/download/v0.11.5/vilesql_0.11.5_Linux_x86_64.tar.gz"
        sha256 "83941657172b009533d0b05adb5fa7e9bfc2a458cc7123aea944a7e283470203"

        def install
          bin.install "vilesql"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/imrany/vilesql/releases/download/v0.11.5/vilesql_0.11.5_Linux_arm64.tar.gz"
        sha256 "8310ad81147de5bfa36e9347a44d87a28145aea016855c76f0ee7e27467fda2b"

        def install
          bin.install "vilesql"
        end
      end
    end
  end

  def caveats
    <<~EOS
      VileSQL will create a data directory at ~/.vilesql on first run.
      This directory contains your database files and configuration.

      Data locations:
        - ~/.vilesql (user data)
        - ~/Library/Application Support/vilesql (macOS)

      To specify a custom data directory, use:
        vilesql --data-dir /path/to/your/data

      Upgrade VileSQL:
        brew upgrade vilesql
        # or use the built-in upgrade command:
        vilesql upgrade

      Check for updates:
        vilesql upgrade --check-only

      To completely uninstall VileSQL and remove all data:
        vilesql uninstall --remove-data
        brew uninstall vilesql

      Or backup before uninstalling:
        vilesql uninstall --remove-data --backup-data
        brew uninstall vilesql
    EOS
  end
end
